### ISSUE TITLE
TypeError: new(): data must be a sequence (got NoneType)

### ISSUE THREAD

**Issue by barrycxg** [facebookresearch/ContactOpt#9]
Hello, thanks for your work. I have a problem when I run ContactOpt on my-provided data.
The log is shown as follow:  
`Traceback (most recent call last):
  File "contactopt/run_user_demo.py", line 79, in <module>
    run_contactopt(args)
  File "/home/barry/文档/contact/contactopt/run_contactopt.py", line 67, in run_contactopt
    for idx, data in enumerate(tqdm(test_loader)):
  File "/home/barry/anaconda3/envs/contactopt/lib/python3.8/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/home/barry/anaconda3/envs/contactopt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/barry/anaconda3/envs/contactopt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/barry/anaconda3/envs/contactopt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/barry/anaconda3/envs/contactopt/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/barry/anaconda3/envs/contactopt/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/barry/anaconda3/envs/contactopt/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/barry/anaconda3/envs/contactopt/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/barry/文档/contact/contactopt/loader.py", line 50, in __getitem__
    out['hand_contact_gt'] = torch.Tensor(sample['ho_gt'].hand_contact)
TypeError: new(): data must be a sequence (got NoneType)`

The data I use is the demo_object.obj and demo_mano.json you provided in the data folder. I find the data you provided without "ho_gt" (loader.py line 49) which leads to this error. How can I solve this problem where I need to provide the ground truth?

**Comment by pgrady3** [comment]
Hi @barrycxg, I'm not sure if I understand your problem correctly. The code successfully runs for you on the demo data, but fails when you try to run it on your own data without ground truth?

If that's the case, I would just feed in garbage ground truth just to make the code happy. You could copy the ground truth from the demo data and feed it in for all of your samples. The ground truth is only used to calculate metrics and to train the network.

**Comment by barrycxg** [comment]
Thanks for your response. I solved this problem. I find that you may have missed the initialization of variable “ho_gt.hand_contact".
I add the code "self.hand_contact = ho.hand_contact" in ”contactopt/hand_object.py“(line 136 load_from_ho function).
Hope you can see if this is the problem.
Thanks for your patience.

**Comment by barrycxg** [comment]
Hello @pgrady3 . I tried to pull my code changes, but failed. I hope the part of the code submitted helps you understand if there is a problem.

**Comment by pgrady3** [comment]
Thank you for the pull request! I'll integrate that change plus a few more soon.

**Comment by barrycxg** [comment]
Thanks for your response.
